name: "CodeQL Analysis"

on:
  push:
    branches: [ main ]
  pull_request:
    # Scans every pull request
    branches: [ main ]
  schedule:
    # Optional: daily scan at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript, python  # Change based on your repo

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql
